### ISSUE TITLE
apply_some should return whether something changed or not

### ISSUE THREAD

**Issue by t-moe** [bengreenier/partially#8]
I find myself in the situation, that I would like to know if an apply_some operation has changed something or not.
To do this I currently derive Default for the Partial Structure and compare the Partial to its default value, but it would be nice if apply_some could simply return a bool saying whether something changed or not....

**Comment by bengreenier** [comment]
Hmm - interesting idea @t-moe - might be a bit tricky if we actually have to do some diffing - Right now, the way that `apply_some` works is to just assign any `Some` value on the partial to the base struct, but we don't currently have any information on if that value is "new".

So, two thoughts here:
1) If you're just looking for an answer to "did we do any assignments" that's easier, we could return `true` when any field on the parital is `Some`, and `false` when all fields are `None`.
2) If you're looking to actually detect if the base struct is significantly modified after `apply_some`, we'd need to actually calculate that diff, maybe with something like [structdiff](https://crates.io/crates/structdiff).

 
It sounds like 1 is more similar to what you're doing at the moment - is that what you're looking for here?

**Comment by t-moe** [comment]
Yes, i mean 1).

**Comment by bengreenier** [comment]
Ok - that should be fairly quick to implement. I'll try to make time to take a look later today.

**Comment by bengreenier** [comment]
landed in `0.2.0`: [crates.io](https://crates.io/crates/partially/0.2.0) - [docs.rs](https://docs.rs/partially/0.2.0/partially/index.html)
